export const data = [
  {
    id: 1,
    logo: "cos-logo.png",
    title: "Centralny Ośrodek Sportowy Spała",
    url: "https://spala.cos.pl/",
  },
  {
    id: 2,
    logo: "logo-mościcki.png",
    title: "Hotel Mościcki",
    url: "http://www.hotelmoscicki.pl/",
  },
  {
    id: 3,
    logo: "hotel prezydent.png",
    title: "Hotel Prezydent",
    url: "https://www.prezydenthotel.pl/",
  },
  {
    id: 4,
    logo: "pzłs-header2-1024x469.png",
    title: "Polski Związek Łyżwiarstwa Szybkiego",
    url: "https://pzls.pl/",
  },
  {
    id: 5,
    logo: "IKS_inowlodz.png",
    title: "IKS Inowłódz",
    url: "http://iksinowlodz.pl/",
  },
  {
    id: 6,
    logo: "janow podlaski logo.png",
    title: "Zamek Biskupi w Janowie Podlaskim",
    url: "https://www.zamekjanowpodlaski.pl/",
  },
  {
    id: 7,
    logo: "logo_powiernik.png",
    title: "Powiernik S.A.",
    url: "https://powiernik.net/",
  },
  {
    id: 8,
    logo: "logo_promien.png",
    title: "NZOZ Promień",
    url: "https://promien.mariowka.net/",
  },
  {
    id: 9,
    logo: "MG-LOGO_KOLOR_poziom.png",
    title: "Mniej Grawitacji",
    url: "http://mniejgrawitacji.pl/",
  },
  {
    id: 10,
    logo: "poswietne.png",
    title: "Gmina Poświętne",
    url: "https://www.poswietne.pl/",
  },
  {
    id: 11,
    logo: "Proem_logo_new-1.png",
    title: "Proem Zako",
    url: "https://proemzako.pl/",
  },
  {
    id: 12,
    logo: "Profit_biuro_rachunkowe.png",
    title: "Profit Biuro Rachunkowe",
    url: "https://profitbialapodlaska.pl/",
  },
  {
    id: 13,
    logo: "zamel_logo.png",
    title: "ZAMEL",
    url: "http://zamel.com.pl/",
  },
  {
    id: 14,
    logo: "gym_house.png",
    title: "Gym House",
    url: "https://gym-house.pl/",
  },
  {
    id: 15,
    logo: "progym.png",
    title: "Progym",
    url: "https://www.facebook.com/progymbp",
  },
  {
    id: 16,
    logo: "fc.png",
    title: "Fabryka Ciała",
    url: "https://www.facebook.com/FabrykaCiala",
  },
  {
    id: 17,
    logo: "ckks.png",
    title: "CKKS",
    url: "http://ckks.pl/",
  },
  {
    id: 18,
    logo: "Logo-MULTON.png",
    title: "Multon",
    url: "http://multon.pl/",
  },
  {
    id: 19,
    logo: "ogrod-marzen.png",
    title: "Ogród Twoich Marzeń",
    url: "https://www.facebook.com/OgrodTwoichMarzen",
  },
  {
    id: 20,
    logo: "kwiat_i_kawa.png",
    title: "Kwiat i Kawa",
    url: "https://www.facebook.com/kwiatikawa/",
  },
  {
    id: 22,
    logo: "teksam.png",
    title: "Teksam Łukasz Daniluk",
    url: "#",
  },
];
